<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <UseArtifactsOutput>true</UseArtifactsOutput>
  </PropertyGroup>
  <PropertyGroup Condition="'$(TargetFramework)' == 'net8.0-windows' or ('$(TargetFramework)' == 'net471' and '$(MSBuildProjectName)' != 'WinFormMarkup')">
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net471'">
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
</Project>
