<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="coverlet.collector" Version="3.1.0" />
    <PackageVersion Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="16.11.0" />
    <PackageVersion Include="RazorEngineCore" Version="2021.3.1" />
    <PackageVersion Include="ReactiveUI.WinForms" Version="18.0.7" />
    <PackageVersion Include="xunit" Version="2.4.1" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="2.4.3" />
  </ItemGroup>
</Project>
