<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFrameworks>net8.0-windows;net471</TargetFrameworks>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <RootNamespace>ReactiveUIApp</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ReactiveUI.WinForms" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Projects\WinFormMarkup\WinFormMarkup.csproj"/>
    </ItemGroup>

</Project>
